#!/usr/bin/env python3
from pathlib import Path
import csv, re, sys
ROOT=Path(__file__).resolve().parents[1]
REQ_DOCS=['docs/GOALOS_COMMERCIALIZATION_STATUS.md', 'docs/GOALOS_PRODUCT_LADDER.md', 'docs/GOALOS_READY_TO_SELL_STATUS.md', 'docs/GOALOS_PROOF_CARD_001_PLAN.md', 'docs/GOALOS_RECURSIVE_WORKFLOW_OS.md', 'docs/GOALOS_CLOUD_MVP_0_2.md', 'docs/GOALOS_PUBLIC_SITE_RELEASE_V8.md', 'docs/GOALOS_WEBSITE_AUTONOMOUS_ACTIONS.md', 'docs/GOALOS_VALIDATION_HOTFIX_V14.md', 'docs/GOALOS_PUBLIC_SITE_ASSET_SYSTEM.md', 'docs/GOALOS_PAID_ARTIFACT_POLICY.md', 'docs/GOALOS_CLAIMS_AND_SAFE_BOUNDARY.md', 'docs/GOALOS_LEGAL_PAYMENTS_BUYER_SUCCESS_SUMMARY.md', 'docs/GOALOS_TAX_ACCOUNTING_CFO_SUMMARY.md', 'docs/GOALOS_COMMUNICATIONS_SUMMARY.md', 'docs/GOALOS_ENGINEERING_ROADMAP.md', 'docs/GOALOS_REPO_AUDIT.md', 'docs/JOBS_ON_BASE_OVERVIEW.md', 'docs/JOBS_ON_BASE_UTILITY_MATRIX.md', 'docs/JOBS_ON_BASE_MARKET_STRATEGY.md', 'docs/JOBS_ON_BASE_SEASON_001.md', 'docs/JOBS_ON_BASE_TECHNICAL_STATUS.md', 'docs/JOBS_ON_BASE_MAINNET_GATES.md', 'docs/JOBS_ON_BASE_SAFE_CLAIMS.md', 'docs/JOBS_ON_BASE_COMMERCIALIZATION_BOUNDARY.md', 'docs/JOBS_ON_BASE_AUDIT_HANDOFF.md', 'docs/COMMERCIALIZATION_PLAN.md', 'docs/COMMERCIALIZATION_TEAM_SCORECARD.md', 'docs/COMMERCIALIZATION_PROOF_OF_VALUE.md', 'docs/COMMERCIALIZATION_PERFORMANCE_VAULT.md']
REQ_TABLES=['goalos_product_ladder.csv', 'goalos_ready_to_sell_status.csv', 'goalos_claim_boundaries.csv', 'goalos_public_site_actions.csv', 'goalos_paid_file_policy.csv', 'goalos_document_inventory.csv', 'goalos_figure_inventory.csv', 'goalos_badge_inventory.csv', 'goalos_validation_rules.csv', 'jobs_on_base_utility_matrix.csv', 'jobs_on_base_market_strategy.csv', 'jobs_on_base_mainnet_gates.csv', 'jobs_on_base_claims_boundary.csv', 'jobs_on_base_contract_status.csv', 'commercialization_kpis.csv', 'commercialization_performance_vault.csv', 'proof_card_001_fields.csv']
FIGS=['goalos_recursive_workflow_loop', 'goalos_product_ladder', 'goalos_proof_led_revenue_loop', 'goalos_cloud_future_architecture', 'goalos_public_site_autonomous_actions_flow', 'goalos_paid_file_guard_flow', 'jobs_on_base_utility_loop', 'jobs_on_base_market_strategy_loop', 'jobs_on_base_mainnet_gate_flow', 'goalos_to_jobs_two_engine_model', 'proof_card_001_flow']
BADGES=['goalos.svg', 'proof-gradient.svg', 'aep-standards.svg', 'no-paid-artifacts.svg', 'website-via-github-actions.svg', 'validation-v14.svg', 'public-site-release-v8.svg', 'cloud-mvp-0-2.svg', 'jobs-on-base.svg', 'jobs-base-sepolia-first.svg', 'jobs-audit-ready-not-audited.svg', 'no-token-investment-claims.svg', 'no-model-self-modification.svg', 'proof-card-001-next.svg', 'recursive-workflow-os.svg']
REQ_README=['What this repository is','What GoalOS is','What Proof Gradient is','What AEP Standards are','GoalOS safe AI boundary','Recursive workflow loop','GoalOS product ladder','Proof Room / Proof Card architecture','Proof Card 001 next milestone','GoalOS Cloud MVP','Website generated by autonomous GitHub Actions','Paid-file policy','Validation and QA','Repository map','Documentation map','Figures and tables','How to validate locally','How to contribute safely','Claims boundary','Shop / apply']
def read(p): return p.read_text(encoding='utf-8',errors='ignore') if p.exists() else ''
def main():
    errors=[]
    for d in REQ_DOCS:
        p=ROOT/d
        if not p.exists(): errors.append(f'missing required doc: {d}')
        elif len(read(p).strip())<300: errors.append(f'doc too thin: {d}')
    for t in REQ_TABLES:
        if not (ROOT/'docs/tables'/t).exists(): errors.append(f'missing required table: docs/tables/{t}')
    for f in FIGS:
        if not (ROOT/'docs/figures'/f'{f}.mmd').exists(): errors.append(f'missing figure source: {f}.mmd')
        if not (ROOT/'docs/figures'/f'{f}.svg').exists(): errors.append(f'missing figure svg: {f}.svg')
    for b in BADGES:
        if not (ROOT/'badges'/b).exists(): errors.append(f'missing badge: badges/{b}')
    readme=read(ROOT/'README.md')
    for sec in REQ_README:
        if sec.lower() not in readme.lower(): errors.append(f'README missing section: {sec}')
    corpus=readme+'\n'+'\n'.join(read(p) for p in (ROOT/'docs').rglob('*.md'))
    for phrase in ['$JOBS is additive','not audited','not mainnet authorized','Base Sepolia first','autonomous GitHub Actions','Do not manually bypass','No proof, no evolution','No eval, no propagation','No rollback, no release','mainnet gates','Proof Card 001']:
        if phrase.lower() not in corpus.lower(): errors.append(f'missing corpus phrase: {phrase}')
    # Internal markdown links
    for p in [ROOT/'README.md', *(ROOT/'docs').rglob('*.md')]:
        text=read(p)
        base=p.parent
        for raw in re.findall(r'!{0,1}\[[^\]]*\]\(([^)]+)\)', text):
            target=raw.split()[0].strip('<>')
            if target.startswith(('http://','https://','#','mailto:')) or not target: continue
            if target.endswith('.zip') and 'standards/AEP-' not in target: errors.append(f'blocked zip link in {p.relative_to(ROOT)}: {target}')
            clean=target.split('#',1)[0].split('?',1)[0]
            if not clean: continue
            q=(base/clean).resolve()
            try: q.relative_to(ROOT.resolve())
            except ValueError: continue
            if not q.exists(): errors.append(f'broken internal link in {p.relative_to(ROOT)}: {target}')
    if errors:
        print('Docs/tables/figures validation failed:', file=sys.stderr)
        print('\n'.join('- '+e for e in errors[:250]), file=sys.stderr); return 1
    print('Docs/tables/figures validation passed.'); return 0
if __name__=='__main__': raise SystemExit(main())
